<template>
  <div class="grid grid-cols-[repeat(auto-fill,minmax(200px,1fr))] gap-3 p-5">
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
    <img class="w-full" src="@/assets/cat.webp" alt="" />
  </div>
</template>
