FROM python:3.11-slim

WORKDIR /code

RUN apt-get update && apt-get install ffmpeg libsm6 libxext6 -y \
    && rm -rf /var/lib/apt/lists/*

COPY app app
COPY ai/models/purr.model.pt ai/models/purr.model.pt
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

RUN useradd -m purr
USER purr

WORKDIR /code/app

CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "main:app"]