name: purr_production

services:
  proxy:
    build:
      context: .
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - purr_network

  frontend:
    build:
      context: ../purr.frontend
    networks:
      - purr_network

  backend:
    build:
      context: ../purr.backend
    networks:
      - purr_network
    volumes:
      - 'backend-storage:/var/www/html/storage'
      - 'backend-bootstrap-cache:/var/www/html/bootstrap/cache'

  mysql:
    image: 'mysql/mysql-server:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - 'mysql:/var/lib/mysql'
    networks:
      - purr_network
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s

  redis:
    image: 'redis:alpine'
    volumes:
      - 'redis:/data'
    networks:
      - purr_network
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

  imageengine:
      build:
        context: ../purr.imageEngine
      networks:
        - purr_network

networks:
  purr_network:
    driver: bridge

volumes:
  backend-storage:
    driver: local

  backend-bootstrap-cache:
    driver: local

  mysql:
    driver: local
    
  redis:
    driver: local